GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldi1hbWFyYSIsImlkIjoiNjAwZDY4ZmIxNzM2MjcyYjQ3MTQyYzE1IiwiaWF0IjoxNjExNTA0MDUwfQ.H8Sd_1wLtN38cVraGSq-rs6lqutW8bVfu5NTif3F4wA

{
  "name": "sample",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT",
  "content": "content",
  "userId": "600d68fb1736272b47142c15"
}

###
PUT http://localhost:3001/api/notes/60082b0a3f404d36b9d9130c
Content-type: application/json

{
  "name": "amara",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT",
  "content":"content"
}

###
DELETE http://localhost:3001/api/notes/60082b0a3f404d36b9d9130c