GET http://localhost:3003/api/blogs
Accept: application/json

###
DELETE http://localhost:3003/api/blogs/600aa6f24a71aadca5d52306

###
PUT http://localhost:3003/api/blogs/600aa6f24a71aadca5d52305
Content-Type: application/json

{
    "title": "HTML is cool",
    "author": "Amara Bamba",
    "url": "http://localhost:3001",
    "likes": 1
  }